#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/WelCheckDB?characterEncoding=UTF-8&serverTimezone=UTC
#    username: root
#    password: rootpass
#    driver-class-name: com.mysql.cj.jdbc.Driver
#
#  jpa:
#    database-platform: org.hibernate.dialect.MySQL8Dialect
#    hibernate:
#      ddl-auto: create
#    show-sql: true


spring: #띄어쓰기 없음
  datasource: #띄어쓰기 2칸
    url: jdbc:h2:tcp://localhost/~/welcheck_backend;
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa: #띄어쓰기 2칸
   hibernate: #띄어쓰기 4칸
     ddl-auto: create #띄어쓰기 6칸
   properties: #띄어쓰기 4칸
     hibernate: #띄어쓰기 6칸
       #show_sql: true #띄어쓰기 8칸
       format_sql: true #띄어쓰기 8칸
